import './globals.css'
import { notojp } from "./utiles/fonts";
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import Sidebar from './components/Sidebar'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="ja-JP" className={`${notojp.variable}`}>
      <body>
        <div className="h-screen flex">
          <Sidebar/>
          <div className="w-screen">{children}</div>
        </div>
      </body>
    </html>
  )
}
