import './globals.css'
import { notojp } from "./utils/fonts";
import type { Metadata } from 'next'
import Sidebar from './components/Sidebar'


export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="ja-JP" className={`${notojp.variable}`}>
      <body>
        <div className="h-screen w-screen flex">
          <div className="w-96"><Sidebar/></div>
          <div className="flex-1 overflow-auto bg-slate-100 h-screen">{children}</div>
        </div>
      </body>
    </html>
  )
}
